version: '3'

services:

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
    - app

  app:
    build:
      context: node
      dockerfile: Dockerfile.prod
    command: npm install
    entrypoint: wait-for db:3306 -t 30 -- node index.js
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/home/node/app
      - ./node/node_modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=nodedb
    - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
      