FROM node:18

WORKDIR /home/node/app

COPY . .

RUN apt-get update && \
    apt-get install -y wget netcat-traditional && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for 

RUN npm install --quiet

EXPOSE 3000