FROM node:18

RUN apt-get update && \
    apt-get install -y wget netcat-traditional && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for 

#caso o id do usuário no container seja diferente de 1000
#RUN usermod -u 501 node

USER node

WORKDIR /home/node

EXPOSE 3000