FROM node:18

WORKDIR /home/node

COPY package*.json ./

RUN npm install --omit-optional && npm cache clean --force

WORKDIR /home/node/app

RUN apt-get update && \
    apt-get install -y wget netcat-traditional && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for 

COPY . .

EXPOSE 3000